### ISSUE TITLE
Unable to run this using just npm I redis-index

### ISSUE THREAD

**Issue by mkmittalofficial** [wankdanker/node-redis-index#1]
I am unable to run application, it's giving Error: Cannot find module '.. /lib/redis-index'
Even if I am installing all the dependency.
But when I add lib and lua folder manually it's running fine. 

Is there any way by which we can exclude those lua and lib folder from the project? I just want to run it by npm install command only

Thanks

**Comment by wankdanker** [comment]
What version of node are you using? `npm i redis-index` works for me.

```bash
npm i redis-index
```

```js
const RedisIndex = require('redis-index')
const index = RedisIndex.createIndex('item', 'item_id');

index.add({ item_id : 1, name : "thing a", type : 100 });
```

**Comment by mkmittalofficial** [comment]
V10.16 , it install the npm I redis-index but when I am running my node application its saying Cannot find module '.. /lib/redis-index'
Also I installed all dependencies too

**Comment by mkmittalofficial** [comment]
![1575302210374-1582688009](https://user-images.githubusercontent.com/43718263/69974044-84eb5580-154a-11ea-9984-34208c43b38b.jpg)

**Comment by mkmittalofficial** [comment]
Hi, it's resolved now... I was using your github repo along with plugin that was causing issue.

Thanks

**Comment by wankdanker** [comment]
Awesome. Glad you got it working.
