### ISSUE TITLE
Any plans to drop requirement for hiredis? It won't compile on MacOS X 10.14 / nodejs v14

### ISSUE THREAD

**Issue by webhype** [wankdanker/node-redis-index#3]
Hi, `redis-index` seems to depend on `hiredis`, which in turn, seems to be an abandoned project. Any chance to use only  [node-redis](https://github.com/NodeRedis/node-redis) which does not necessarily depend on `hiredis`? The performance gains from using `hiredis` are supposed to be minimal, save for the most strenuous situations.

**Note that `node-redis` does not necessarily require `hiredis`. They just work together if desired. I noticed in your `package.json` that you require `hiredis` -- are you sure it is needed as a dependency in your project?**

When trying `$ npm i redis-index`, it tries to compile or recompile `hiredis`, and I get this issue exactly: [https://github.com/redis/hiredis-node/issues/143](https://github.com/redis/hiredis-node/issues/143) which has remained unanswered be the project owner for almost a year. Title page on GitHub says `hiredis-node is deprecated, unmaintained and not updated in forever. Use node-redis.` The root issue seems to be that `hiredis` won't compile on node versions > 8 on MacOS.

`brew install hiredis` seems to download "something already compiled for MacOS", but it doesn't make `npm i hiredis` work and I am not clear how the two relate, if it all. In any case, `hiredis` is a mess and was abandoned as of Node v8. I want to strongly plead to make your project independent from it.

Thanks for listening!

**Comment by wankdanker** [comment]
Hey @webhype. Thank you for the heads up about this. 

This module does use `node-redis`, but also includes the `hiredis` module which based on my understanding at the time was used by `node-redis` to get some sort of optimization when interfacing with a redis server.

So, maybe the correct course of action here would be to add `hiredis` to `optionalDependencies` in `package.json`. (https://docs.npmjs.com/files/package.json#optionaldependencies)

Thoughts?

**Comment by webhype** [comment]
Either way seems "correct" to me. It's my understanding that node-redis supports/supported hiredis for its fans back in the day, because it's compiled C++ and eeks out a (mostly academic?) performance gain. I don't know if optionally (for node versions 8 and below?) hiredis is still being used by node-redis or not, or if it only uses "native nodejs" sockets any more. In any case, your project should probably no longer "depend" on it... thanks for fixing it! 😉

**Comment by wankdanker** [comment]
This update has been published to npm as redis-index@4.0.0.
