### ISSUE TITLE
When storeObject=false and literal=false, returns unexpected results

### ISSUE THREAD

**Issue by webhype** [wankdanker/node-redis-index#5]
The expected result of this code is just `4`, the unique index for `brenda mcgill`, who's the only hungry thing in the bunch. Instead it returns `[1, 4]`. When I turn `storeObject: true`, it returns only row 4 as expected, albeit the entire row. However, in my application I don't want to clone the entire database to Redis:

				const ri = RedisIndex.createIndex({
					key: 'ri:test',	// Redis key namespace
					index: 'unique',	// he attribute of the document whose value uniquely identifies that object
					schema: {
						description: {literal: false},
						name: {
							literal: true	// index complete phrase with spaces, e.g. 'brenda mcgill' not as 'brenda' and 'mcgill'
						},
						boolz: {type: 'boolean'}
					},
					schemaOnly: true,
					storeObject: false, // *** TOGGLE THIS TO SEE THE BUG ***
					createClient: () => { return myStuff.client.duplicate(); },
					closeClient: (client) => { client.quit(); },	

				});

				const docs = [
					{unique: 1, name: 'steve', description: 'hello there thing', type: 1, when: new Date(), value: 100, boolz: false},
					{unique: 2, name: 'sam', description: 'this thing is named sam', type: 1, when: new Date(), value: 50, boolz: false},
					{unique: 3, name: 'george', description: 'and here is one george', type: 2, when: new Date(), value: 75, boolz: true},
					{unique: 4, name: 'brenda mcgill', description: 'i am a hungry thing', type: 2, when: new Date(), value: 30, boolz: false},
				];
				let proms = [];

				for (let d of docs) {
					proms.push(ri.add(d));
				}
				await Promise.all(proms);

				{
					/** @type {RedisIndexSearch} */
					let ris = await ri.search({description: 'hungry'});
					const result = await ris.exec();
					console.log(result);
				}

				// Remove all 

				for (let d of docs) {
					proms.push(ri.del(d));
				}
				await Promise.all(proms);

**Comment by webhype** [comment]
The following code doesn't find `'brenda mcgill'` in its exact form in row 4. About the bug described above, it seems that the numeric array returned is a literal Redis result, so only every even element counts and every odd element is set to "1" -- could that be?	

			const ri = RedisIndex.createIndex({
					key: 'ri:test',	// Redis key namespace
					index: 'unique',	// the attribute of the document whose value uniquely identifies that object
					schema: {
						name: {literal: true},	// index complete phrase with spaces, e.g. 'brenda mcgill' not as 'brenda' and 'mcgill'
						boolz: {type: 'boolean'},
					},
					schemaOnly: true, // only index fields that exist in the schema
					storeObject: false,	// store the document in redis or not
					createClient: () => { return myStuff.redis.duplicate(); },
					closeClient: (client) => { client.quit(); },	// do nothing, leave client open
				});

				const docs = [
					{unique: 1, name: 'steve', description: 'hello there thing', type: 1, when: new Date(), value: 100, boolz: false},
					{unique: 2, name: 'sam', description: 'this thing is named sam', type: 1, when: new Date(), value: 50, boolz: false},
					{unique: 3, name: 'george', description: 'and here is one george', type: 2, when: new Date(), value: 75, boolz: true},
					{unique: 4, name: 'brenda mcgill', description: 'i am a hungry thing', type: 2, when: new Date(), value: 30, boolz: false},
				];
				let proms = [];

				for (let d of docs) {
					proms.push(ri.add(d));
				}
				await Promise.all(proms);

				{
					/** @type {RedisIndexSearch} */
					let ris = await ri.search({name: 'brenda mcgill'});
					const result = await ris.exec();
					console.log(result);
				}

**Comment by wankdanker** [comment]
> About the bug described above, it seems that the numeric array returned is a literal Redis result

This is what my intuition was telling me. Am looking at this now.

**Comment by wankdanker** [comment]
The '1' is the score. So, if you create another record that has 'hungry' in the description twice, you'll find that it will have a '2'

```js
const ri = RedisIndex.createIndex({
        key: 'ri:test',	// Redis key namespace
        index: 'unique',	// he attribute of the document whose value uniquely identifies that object
        schema: {
            description: {literal: false},
            name: {
                literal: true	// index complete phrase with spaces, e.g. 'brenda mcgill' not as 'brenda' and 'mcgill'
            },
            boolz: {type: 'boolean'}
        },
        schemaOnly: true,
        storeObject: false, // *** TOGGLE THIS TO SEE THE BUG ***
    });

    const docs = [
        {unique: 1, name: 'steve', description: 'hello there thing', type: 1, when: new Date(), value: 100, boolz: false},
        {unique: 2, name: 'sam', description: 'this thing is named sam', type: 1, when: new Date(), value: 50, boolz: false},
        {unique: 3, name: 'george', description: 'and here is one george', type: 2, when: new Date(), value: 75, boolz: true},
        {unique: 4, name: 'brenda mcgill', description: 'i am a hungry thing', type: 2, when: new Date(), value: 30, boolz: false},
        {unique: 6, name: 'larry mcgill', description: 'i am a hungry hungry thing', type: 2, when: new Date(), value: 30, boolz: false},
    ];
    let proms = [];

    for (let d of docs) {
        proms.push(ri.add(d));
    }
    await Promise.all(proms);

    {
        /** @type {RedisIndexSearch} */
        let ris = await ri.search({description: 'hungry'});
        const result = await ris.exec();
        console.log(result);
    }

    // Remove all 

    for (let d of docs) {
        proms.push(ri.del(d));

    }

    await Promise.all(proms);
```
=> [ '4', '1', '6', '2' ]

**Comment by wankdanker** [comment]
Specifying a type for name fixes the other issue you are having.

```js
const ri = RedisIndex.createIndex({
        key: 'ri:test',	// Redis key namespace
        index: 'unique',	// the attribute of the document whose value uniquely identifies that object
        schema: {
            name: { type: String, literal: true},	// index complete phrase with spaces, e.g. 'brenda mcgill' not as 'brenda' and 'mcgill'
            boolz: {type: Boolean},
        },
        schemaOnly: true, // only index fields that exist in the schema
        storeObject: false	// store the document in redis or not
    });
```

**Comment by wankdanker** [comment]
I don't know why that works, though. Everything should work with a type that is a string of the type. Not the literal type (eg: String).

**Comment by webhype** [comment]
Seems like it's working with the hints you suggested thank you! You've literally programmed a whole RDBMS on top of Redis, awesome!!

The literal search for `'brenda mcgill'` works both with `String` (class) or ´'String'` (the word, in quotes). The resulting score is 0 always, though, oddly. Shouldn't it be 1 for 1 match?

**Comment by wankdanker** [comment]
Sorry, my previous suggestion was not the correct solution.

```js
const ri = RedisIndex.createIndex({
        key: 'ri:test',	// Redis key namespace
        index: 'unique',	// the attribute of the document whose value uniquely identifies that object
        schema: {
            name: { type: 'string', literal: true},	// index complete phrase with spaces, e.g. 'brenda mcgill' not as 'brenda' and 'mcgill'
            boolz: { type: 'boolean' },
        },
        schemaOnly: true, // only index fields that exist in the schema
        storeObject: false	// store the document in redis or not
    });

    const docs = [
        {unique: 1, name: 'steve', description: 'hello there thing', type: 1, when: new Date(), value: 100, boolz: false},
        {unique: 2, name: 'sam', description: 'this thing is named sam', type: 1, when: new Date(), value: 50, boolz: false},
        {unique: 3, name: 'george', description: 'and here is one george', type: 2, when: new Date(), value: 75, boolz: true},
        {unique: 5, name: 'brenda mcgill', description: 'i am a hungry thing', type: 2, when: new Date(), value: 30, boolz: false},
    ];
    let proms = [];

    for (let d of docs) {
        proms.push(ri.add(d));
    }
    await Promise.all(proms);

    {
        /** @type {RedisIndexSearch} */
        let ris = await ri.search({
            name: RedisIndex.exactly('brenda mcgill')
        });
        const result = await ris.exec();
        console.log(result);
    }
```

Notice this:
```js
let ris = await ri.search({
    name: RedisIndex.exactly('brenda mcgill')
});
```

But, it kinda depends on how you want to be able to search that field. If you want to be able to find individual whole words, then you might want to have `literal : false`. I only ever use `literal : true` when the field is some sort of identifier for the object that may potentially contain spaces.

**Comment by wankdanker** [comment]
BTW, if you are familiar with redis commands at all, you can run your code with `DEBUG=redis-index*` to see what is going on behind the scenes. It may help you see what is going on.

**Comment by webhype** [comment]
Thanks!! Your project is full of secret features 😃 but all very well thought out...

**Comment by wankdanker** [comment]
Lol. It's mostly secrets. :)
