### ISSUE TITLE
Using query statements

### ISSUE THREAD

**Issue by devpilot-official** [wankdanker/node-redis-index#7]
Hello,

I would like to use query statement something like greater than and less than. is this possible? if yes can i get a peek at it.

Example in mongoose: db.find({ quantity: { $gte: 1, $lte: 5 }  });

I want to carry out this process mainly on dates.

So, assuming I have my dates stored in redis-index as date: 04-01-2020, I want to search for all dates from 01-01-2020 to 05-01-2020

index.search({ date: { gte: 01-01-2020, lte: 05-01-2020 } }).

Thanks in advance.

Regards.

**Comment by wankdanker** [comment]
Hi!

I don't believe I have ever tested this with dates, so, it probably won't work. But, if it were to work, this is how it would be done:

```js
index.search({ date : index.gte('01-01-2020') }).and({ date : index.lte('05-01-2020') });
```

There are a bunch of comparisons that can be used which can be found here:

https://github.com/wankdanker/node-redis-index/blob/master/lib/comparisons.js

Hope this helps.

**Comment by devpilot-official** [comment]
Thanks for the reply, i will try this out

**Comment by devpilot-official** [comment]
> Hi!
> 
> I don't believe I have ever tested this with dates, so, it probably won't work. But, if it were to work, this is how it would be done:
> 
> ```js
> index.search({ date : index.gte('01-01-2020') }).and({ date : index.lte('05-01-2020') });
> ```
> 
> There are a bunch of comparisons that can be used which can be found here:
> 
> https://github.com/wankdanker/node-redis-index/blob/master/lib/comparisons.js
> 
> Hope this helps.

This works like acharm
